services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: platform
      MYSQL_USER: ernest1
      MYSQL_PASSWORD: user123
    container_name: backend-exam
    volumes:
      - ./service-platform-app-mysql:/var/lib/mysql